"""empty message

Revision ID: 494167736e42
Revises: 
Create Date: 2020-05-27 16:41:42.992139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494167736e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('role_flags', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_active'), 'auth_users', ['active'], unique=False)
    op.create_index(op.f('ix_auth_users_role_flags'), 'auth_users', ['role_flags'], unique=False)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('hash_2_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('time_to_live', sa.Integer(), nullable=True),
    sa.Column('expire_after_first_access', sa.Boolean(), nullable=False),
    sa.Column('last_access', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hash_2_params_hash'), 'hash_2_params', ['hash'], unique=True)
    op.create_table('mail_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('sender_name', sa.String(length=128), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('receiver_name', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_mail_queue_sender'), 'mail_queue', ['sender'], unique=False)
    op.create_index(op.f('ix_mail_queue_sent'), 'mail_queue', ['sent'], unique=False)
    op.create_index(op.f('ix_mail_queue_subject'), 'mail_queue', ['subject'], unique=False)
    op.create_table('minify',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('s_hash_2_params',
    sa.Column('id', sa.CHAR(length=64), nullable=False),
    sa.Column('active_stage', sa.CHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s_hash_2_params_active_stage'), 's_hash_2_params', ['active_stage'], unique=False)
    op.create_table('s_session_token',
    sa.Column('id', sa.CHAR(length=64), nullable=False),
    sa.Column('active_stage', sa.CHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s_session_token_active_stage'), 's_session_token', ['active_stage'], unique=False)
    op.create_table('s_users',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('active_stage', sa.CHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s_users_active_stage'), 's_users', ['active_stage'], unique=False)
    op.create_table('sequencer',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('s_partition', sa.CHAR(length=2), nullable=False),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.Column('active_stage', sa.CHAR(length=3), nullable=False),
    sa.Column('check_sum_size', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('s_table', sa.String(length=64), nullable=False),
    sa.Column('ordered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('s_table')
    )
    op.create_table('hash_2_params_history_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_hash_2_params', sa.Integer(), nullable=False),
    sa.Column('log_time', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_hash_2_params'], ['hash_2_params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_tokens',
    sa.Column('id', sa.CHAR(length=64), nullable=False),
    sa.Column('id_user', sa.CHAR(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_tokens_active'), 'session_tokens', ['active'], unique=False)
    op.create_index(op.f('ix_session_tokens_type'), 'session_tokens', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_session_tokens_type'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_active'), table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_table('hash_2_params_history_log')
    op.drop_table('sequencer')
    op.drop_index(op.f('ix_s_users_active_stage'), table_name='s_users')
    op.drop_table('s_users')
    op.drop_index(op.f('ix_s_session_token_active_stage'), table_name='s_session_token')
    op.drop_table('s_session_token')
    op.drop_index(op.f('ix_s_hash_2_params_active_stage'), table_name='s_hash_2_params')
    op.drop_table('s_hash_2_params')
    op.drop_table('options')
    op.drop_table('minify')
    op.drop_index(op.f('ix_mail_queue_subject'), table_name='mail_queue')
    op.drop_index(op.f('ix_mail_queue_sent'), table_name='mail_queue')
    op.drop_index(op.f('ix_mail_queue_sender'), table_name='mail_queue')
    op.drop_table('mail_queue')
    op.drop_index(op.f('ix_hash_2_params_hash'), table_name='hash_2_params')
    op.drop_table('hash_2_params')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_role_flags'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_active'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
