"""created table

Revision ID: 7a2f58705a10
Revises: f58ba5b194da
Create Date: 2020-05-22 13:42:39.420986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2f58705a10'
down_revision = 'f58ba5b194da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minify', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('minify', sa.Column('short_url', sa.String(), nullable=False))
    op.drop_column('minify', 'surl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minify', sa.Column('surl', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('minify', 'short_url')
    op.drop_column('minify', 'created')
    # ### end Alembic commands ###
